import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  en: {
    welcome: "Hello! How can I help you today?",
    chatTitle: "AI Conversation",
    sideMenu: "Side Menu",
    english: "English",
    spanish: "Spanish",
    french: "French",
    german: "German",
    chinese: "Chinese",
    generateTitlePrompt: "Generate a short, relevant and interesting chat title based on this message.",
    translatePrompt: "Translate the following text to {language}:",
    errorMessage: "Oops! Something went wrong.",
    clear: "Clear",
    loadPreviousMessages: "Load Previous Messages",
    aiTyping: "AI is typing...",
    chatInputPlaceholder: "Chat input",
    send: "Send",
    close: "Close",
    chatHistory: "Chat history",
    delete: "Delete",
    selectLanguage: "Select Language",
    deleteAllChats: "Delete All Chats",
    deleteAllChatsTitle: "Delete All Chats",
    deleteAllChatsMessage: "Are you sure you want to delete all chats?",
    cancel: "Cancel",
    deleteAllChatsSuccess: "All chats deleted successfully!",
    newConversation: "New Conversation",
  },
  es: {
    welcome: "¡Hola! ¿Cómo puedo ayudarte hoy?",
    chatTitle: "Conversación AI",
    sideMenu: "Menú Lateral",
    english: "Inglés",
    spanish: "Español",
    french: "Francés",
    german: "Alemán",
    chinese: "Chino",
    generateTitlePrompt: "Genera un título de chat corto, relevante e interesante basado en este mensaje.",
    translatePrompt: "Traduce el siguiente texto al {language}:",
    errorMessage: "¡Vaya! Algo salió mal.",
    Clear: "Limpiar",
    loadPreviousMessages: "Cargar mensajes anteriores",
    aiTyping: "La IA está escribiendo...",
    chatInputPlaceholder: "Entrada de chat",
    send: "Enviar",
    close: "Cerrar",
    chatHistory: "Historial de chat",
    delete: "Eliminar",
    selectLanguage: "Seleccionar idioma",
    deleteAllChats: "Eliminar todos los chats",
    deleteAllChatsTitle: "Eliminar todos los chats",
    deleteAllChatsMessage: "¿Estás seguro de que deseas eliminar todos los chats?",
    cancel: "Cancelar",
    deleteAllChatsSuccess: "¡Todos los chats eliminados con éxito!",
    newConversation: "Nueva conversación",
  },
  fr: {
    welcome: "Bonjour! Comment puis-je vous aider aujourd'hui?",
    chatTitle: "Conversation AI",
    sideMenu: "Menu Latéral",
    english: "Anglais",
    spanish: "Espagnol",
    french: "Français",
    german: "Allemand",
    chinese: "Chinois",
    generateTitlePrompt: "Générez un titre de chat court, pertinent et intéressant basé sur ce message.",
    translatePrompt: "Traduisez le texte suivant en {language} :",
    errorMessage: "Oups! Quelque chose a mal tourné.",
    clear: "Effacer",
    loadPreviousMessages: "Charger les messages précédents",
    aiTyping: "L'IA est en train d'écrire...",
    chatInputPlaceholder: "Entrée de chat",
    send: "Envoyer",
    close: "Fermer",
    chatHistory: "Historique des chats",
    delete: "Supprimer",
    selectLanguage: "Choisir la langue",
    deleteAllChats: "Supprimer tous les chats",
    deleteAllChatsTitle: "Supprimer tous les chats",
    deleteAllChatsMessage: "Êtes-vous sûr de vouloir supprimer tous les chats?",
    cancel: "Annuler",
    deleteAllChatsSuccess: "Tous les chats ont été supprimés avec succès!",
    newConversation: "Nouvelle conversation",
  }
});

export default strings;
